---
sudo: false
language: python
python: "2.7"
services:
  - docker
install:
  - pip install ansible
  - pip install docker-py
  - pip install molecule --pre
script: molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
