---
- name: Install pip
  package:
    name: python-pip
    state: present

- name: >
      Add tarsnap apt key (if task fails, see https://www.tarsnap.com/pkg-deb.html for latest key and override `backup__tarsnap_apt_key`)
  apt_key:
    url: https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc
    state: present
    id: "{{ backup__tarsnap_apt_key }}"

- name: Add tarsnap apt repo
  apt_repository:
    repo: "deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./"
    filename: tarsnap.list
    state: present

- name: Install tarsnap
  package:
    name: tarsnap
    state: present

- name: Copy tarsnap configuration file
  template:
    src: templates/tarsnap.conf.j2
    dest: /etc/tarsnap.conf
    mode: 0644
    owner: root
    group: root

- name: Install pexpect module globally
  # required by the expect module
  pip:
    name: pexpect
    state: present

- name: Check for supplied tarsnap key
  delegate_to: localhost
  stat:
    path: "files/{{ ansible_hostname }}.key"
  register: local_key
  ignore_errors: true

- name: Generate tarsnap key and register host
  expect:
    command: tarsnap-keygen --keyfile {{ backup__tarsnap_keyfile }} --user {{ backup__tarsnap_username }} --machine {{ ansible_hostname }}
    responses:
      password: "{{ backup__tarsnap_password }}"
    creates: "{{ backup__tarsnap_keyfile }}"
  notify:
    - collect tarsnap key
    - print tarsnap key
    - restore tarsnap cache
  register: tarsnap_keygen
  # the tarsnap key file in the test environment isn't a valid one
  when: not local_key.stat.exists and backup__env != 'test'

- name: Copy supplied tarsnap key
  copy:
    src: "files/{{ ansible_hostname }}.key"
    dest: "{{ backup__tarsnap_keyfile }}"
  when: local_key.stat.exists

- name: Set permissions on tarsnap key
  file:
    path: "{{ backup__tarsnap_keyfile }}"
    mode: 0600
    owner: root
    group: root

- name: Rebuild tarsnap cache
  become: true
  command: 'tarsnap --fsck'
  # the tarsnap key file in test is not a valid one
  # rebuilding the cache is long so it is optional
  when: backup__env != 'test' or backup__rebuild_cache
  changed_when: false

- name: Install tarsnapper
  pip:
    name: tarsnapper
    state: present

- name: Copy tarsnapper config file
  template:
    src: templates/tarsnapper.yml.j2
    dest: "{{ backup__tarsnapper_config_file }}"
    mode: 0600
    owner: root
    group: root

- name: Create tarsnapper log file
  copy:
    dest: "{{ backup__tarsnapper_log_file }}"
    content: ''
    force: no
    mode: 0600
    owner: root
    group: root

- name: Get path to tarsnapper command
  command: 'which tarsnapper'
  register: tarsnapper_full_path
  changed_when: false

- name: Install cron
  package:
    name: cron
    state: present

- name: Add backup task to cron
  cron:
    name: Backup to tarsnap
    job: "{{ tarsnapper_full_path.stdout }} -c {{ backup__tarsnapper_config_file }} make >> /var/log/tarsnapper.log 2>&1"
    minute: "{{ backup__cron_minute }}"
    hour: "{{ backup__cron_hour }}"
    dom: "{{ backup__cron_dom }}"
    month: "{{ backup__cron_month }}"
    dow: "{{ backup__cron_dow }}"
